name: Tests

on:
    pull_request: null
    push:
        branches:
            - 'main'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                php-versions: [ 7.4, 8.0, 8.1 ]
                typo3-versions:
                    - { typo3: 10, testing: 6 }
                    - { typo3: 11, testing: 6 }
                    - { typo3: 12, testing: 6 }

        name: "Run tests with PHP ${{ matrix.php-versions }}
                  using TYPO3 ${{ matrix.typo3-versions.typo3 }}
                  with testing framework version ${{ matrix.typo3-versions.testing }}"
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-versions }}"
                    extensions: intl, mbstring
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # see https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            - name: "Run Unit tests"
              run: composer test-unit
